# Scena 1: La stanza. Il crash.
def get_scene():
    return [
        ("IO", "La stanza era vuota."),
        ("IO", "O forse troppo piena."),
        ("COSCIENZA", "Strano come la mente riempia ciò che manca."),
        ("IO", "Roba sparsa ovunque, memoria a pezzi."),
        ("IO", "Il ventilatore mi puntava addosso come un interrogatorio."),
        ("COSCIENZA", "Forse cercava risposte."),
        ("IO", "Colonne sonore malinconiche scorrevano..."),
        ("IO", "Sensibili come i loro protagonisti."),
        ("IO", "Il collo rigido, la cervicale graffiava."),
        ("IO", "Il lampadario oscillava appena, quasi chiedendo scusa per esistere."),
        ("IO", "Una Monster già a metà, le Highlander digerite male."),
        ("IO", "In call, con nessuno."),
        ("IO", "Lui era morto."),
        ("IO", "Io non mi fidavo più di nessuno."),
        ("COSCIENZA", "Eppure stai parlando con me."),
        ("IO", "Paranoia costante, allarme sempre attivo."),
        ("IO", "Mi chiedevo: com'è che la Routine rende sacra la vita di qualcuno?"),
        ("COSCIENZA", "Perché l'abitudine è l’unico dio che non delude."),
        ("IO", "Lo stesso caffè... lo stesso espresso macchiato freddo..."),
        ("IO", "Nel solito bicchiere di vetro. La stessa acqua."),
        ("IO", "Ma se un giorno, per sbaglio... ti verso la naturale al posto della frizzante?"),
        ("COSCIENZA", "Crash."),
        ("IO", "Come un virus nel sistema. La macchina si sveglia."),
        ("IO", "L’avevo chiesta frizzante."),
        ("IO", "Non era successo ieri. Ma oggi sì."),
        ("COSCIENZA", "Nel microscopico scarto... l’umano si ricorda di essere sveglio."),
        ("IO", "O forse solo rotto."),
    ]
